language: php

php:
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install: composer update --prefer-dist $COMPOSER_FLAGS

script:
  - php vendor/bin/phpunit --verbose --coverage-text --coverage-clover coverage.clover
  - phpenv config-rm xdebug.ini || true
  - php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format php-clover coverage.clover
